name: Mirror repo to S3

on:
  schedule:
    - cron: '* * * * *'  # Run every 5 minutes
jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo to be backed up
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: repo-to-backup
          ref: 'dev-branch'

      - name: Backup repo to s3
        uses: sammcj/backup-git-to-s3-action@main
        with:
          s3-bucket: 'anandaswati'
          s3-prefix: 'repo-to-backup'
          s3-region: 'us-east-1'
          repository-path: './repo-to-backup/'
          temp-dir: '/tmp'
          tar-command: 'tar -czvf'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
